baseURL = 'https://www2.giancampo.com/'
languageCode = 'en-us'
title = 'Gianluca Campo: Exploring Digital Analytics, SEO, Digital Marketing Data, and Automation'
theme = 'hugo-bearblog'
publishDir = 'docs'
